### ISSUE TITLE
Date Picker Range Issue

### ISSUE THREAD

**Issue by AlexandraMadalina** [carbon-design-system/carbon-components-angular#2762]
## Detailed description

Date Picker Range Cannot read properties of undefined (reading '0')

When you focus on an input from the date picker range it throws an error Cannot read properties of undefined (reading '0')
It can be reproduce on  https://angular.carbondesignsystem.com/?path=/docs/components-date-picker--docs
<img width="1590" alt="Screenshot 2024-01-23 at 11 46 39" src="https://github.com/carbon-design-system/carbon-components-angular/assets/47785112/f09c5c87-8262-4099-b3d4-12a949b946a4">

**Comment by Akshat55** [comment]
This is specifically a storybook docs page issue... I can assure you that it works in your angular app. There are still a few issues with storybook/angular we have to resolve.

Thank you for reporting this!

**Comment by Akshat55** [comment]
@AlexandraMadalina Could you still produce the issue in storybook? I've updated it recently and I've fixed this issue by passing a unique ID into datepicker. Keep in mind, you do not have to pass in an ID as it will automatically assign it a unique ID.

**Comment by AlexandraMadalina** [comment]
in storybook it works fine now, in my app I still have the issue

**Comment by Akshat55** [comment]
Are you passing an id element to the date picker? If yes, could you try removing it or ensuring the id is unqiue?
